---


- hosts: 192.168.99.101
  become: true
  vars:
       username: fannu123465
       home_dir: "/home/{{ username }}"
       authorized_key_file: "{{ home_dir }}/.ssh/authorized_keys"
       ssh_public_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  tasks:
    - name: Create new user
      user:
        name: "{{ username }}"
        shell: /bin/bash
        create_home: yes
    - name: Add SSH public key to authorized_keys file
      authorized_key:
         user: "{{ username }}"
         key: "{{ ssh_public_key }}"
         state: present
         exclusive: yes
         manage_dir: yes
         path: "{{ authorized_key_file }}"
    - name: Disable SSH password authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^PasswordAuthentication"
        line: "PasswordAuthentication no"
        state: present
      notify: restart sshd
    - name: Create directory in /opt/
      file:
        path: /opt/new_directory
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: "0755"

  handlers:

    - name: restart sshd
      service:
        name: sshd
        state: restarted
